c.utf-8: utf8.c File Reference
utf8.c File Reference
#include "utf8_impl.h"
Functions
static utf8_const_inline int utf8_state_from_bit (uint16_t bit)
Convert a parser state from a bit flag representation to the corresponding parser state enumeration.
static utf8_force_inline bool utf8_get_state (struct utf8 *const u8p, enum utf8_st8 *const st8)
Get the parser's current state as a state enumeration.
static utf8_const_inline uint16_t utf8_get_allowed_next_states (enum utf8_st8 st8)
Get a mask of state flags comprising the states allowed after st8.
static utf8_const_inline bool utf8_done (struct utf8 const *const u8p)
Check if the UTF-8 parser has finished processing a character.
static utf8_const_inline bool utf8_st8_is_leading_byte (enum utf8_st8 st8)
Check if a parser state enumeration represents a UTF-8 leading byte or an ASCII byte.
static utf8_force_inline void utf8_push_to_cache (struct utf8 *const u8p, enum utf8_st8 st8, uint8_t byte)
Write a byte to a specific position inside the parser cache.
static utf8_force_inline bool utf8_set_state (struct utf8 *const u8p, enum utf8_st8 *const st8, uint8_t byte)
Update the UTF-8 parser state and cache based on an input byte.
uint8_t const * utf8_parse_next_code_point (struct utf8 *const u8p, uint8_t const *ptr)
Variables
static constexpr const uint16_t utf8_lut []
Lookup table.
static constexpr const uint16_t utf8_dst [16] = { [utf8_asc ] = utf8_bit(asc) | utf8_bit(lb2) | utf8_bit(lb3_e0) | utf8_bit(lb3) | utf8_bit(lb3_ed) | utf8_bit(lb4_f0) | utf8_bit(lb4) | utf8_bit(lb4_f4), [utf8_lb2 ] = utf8_bit(cb1), [utf8_lb3_e0] = utf8_bit(cb2_e0), [utf8_lb3 ] = utf8_bit(cb2), [utf8_lb3_ed] = utf8_bit(cb2_ed), [utf8_lb4_f0] = utf8_bit(cb3_f0), [utf8_lb4 ] = utf8_bit(cb3), [utf8_lb4_f4] = utf8_bit(cb3_f4), [utf8_cb3_f4] = utf8_bit(cb2), [utf8_cb3 ] = utf8_bit(cb2), [utf8_cb3_f0] = utf8_bit(cb2), [utf8_cb2_ed] = utf8_bit(cb1), [utf8_cb2 ] = utf8_bit(cb1), [utf8_cb2_e0] = utf8_bit(cb1), [utf8_cb1 ] = utf8_bit(asc) | utf8_bit(lb2) | utf8_bit(lb3_e0) | utf8_bit(lb3) | utf8_bit(lb3_ed) | utf8_bit(lb4_f0) | utf8_bit(lb4) | utf8_bit(lb4_f4), [utf8_ini ] = utf8_bit(asc) | utf8_bit(lb2) | utf8_bit(lb3_e0) | utf8_bit(lb3) | utf8_bit(lb3_ed) | utf8_bit(lb4_f0) | utf8_bit(lb4) | utf8_bit(lb4_f4), }
Function Documentation
utf8_done()
utf8_const_inline bool utf8_done (struct utf8 const *const u8p) static
Check if the UTF-8 parser has finished processing a character.
This function checks the state of the UTF-8 parser to determine if it has successfully parsed a complete character. The parser is considered done if the current state represents an ASCII byte or a continuation byte.
Parameters
u8p A pointer to the UTF-8 parser.
Returns
true if the parser has finished processing a character, otherwise false.
Referenced by utf8::utf8_parse_next_code_point().
utf8_get_allowed_next_states()
utf8_const_inline uint16_t utf8_get_allowed_next_states (enum utf8_st8 st8) static
Get a mask of state flags comprising the states allowed after st8.
Parameters
st8 A parser state enumeration.
Returns
Mask of state flags representing the allowed states, or 0 if st8 is not a valid state enumeration.
Referenced by utf8_set_state().
utf8_get_state()
utf8_force_inline bool utf8_get_state (struct utf8 *const u8p, enum utf8_st8 *const st8) static
Get the parser's current state as a state enumeration.
Note that this is not a pure getter, as utf8::error is clobbered on failure. Take precautions to save it if needed.
Parameters
u8p The UTF-8 parser. The error field is set on failure without regard to its current state.
st8 Where to store the state enumeration on success. Not modified on failure. Must not be nullptr.
Returns
true on success. On failure sets ut8::error to ENOTRECOVERABLE and returns false.
Referenced by utf8::utf8_parse_next_code_point().
utf8_push_to_cache()
utf8_force_inline void utf8_push_to_cache (struct utf8 *const u8p, enum utf8_st8 st8, uint8_t byte) static
Write a byte to a specific position inside the parser cache.
This function writes a byte into the parser cache at the position determined by the current parser state (as indicated by the st8 parameter).
If the state represents a leading byte or an ASCII byte, the cache is reset, the length of the expected UTF-8 sequence is written to the length field, and the byte value is written to the first buffer position.
If the state represents a continuation byte, the destination position is calculated from the state in the context of the length field value. (This is necessary because some parser states are shared between state transition paths; for example, all multi-byte sequences terminate in the utf8_cb1 state, so determining the correct buffer position requires knowing the expected sequence length as well.)
Parameters
u8p The UTF-8 parser to update.
st8 The current parser state expressed as a state enumeration.
byte The byte to push into the cache.
Referenced by utf8_push_to_cache(), and utf8_set_state().
utf8_set_state()
utf8_force_inline bool utf8_set_state (struct utf8 *const u8p, enum utf8_st8 *const st8, uint8_t byte) static
Update the UTF-8 parser state and cache based on an input byte.
This function validates the input byte against the state transition rules which apply to the current parser state. If the byte is a valid next byte, the parser state is updated accordingly and the byte is pushed into the parser's byte cache.
Parameters
u8p The UTF-8 parser to update. The error field is set on failure.
st8 On input a pointer to the current parser state expressed as a state enumeration. On output the updated state enumeration if the byte is valid, otherwise unchanged. Must not be nullptr.
byte The byte to process and push into the parser cache.
Returns
true if the state update was successful. If the update fails, sets utf8::error to EILSEQ and returns false.
Referenced by utf8::utf8_parse_next_code_point(), and utf8_set_state().
utf8_st8_is_leading_byte()
utf8_const_inline bool utf8_st8_is_leading_byte (enum utf8_st8 st8) static
Check if a parser state enumeration represents a UTF-8 leading byte or an ASCII byte.
Parameters
st8 The state enumeration to check.
Returns
true if st8 is a leading byte or ASCII, otherwise false.
Referenced by utf8_push_to_cache().
utf8_state_from_bit()
utf8_const_inline int utf8_state_from_bit (uint16_t bit) static
Convert a parser state from a bit flag representation to the corresponding parser state enumeration.
If the return value is not negative, it is guaranteed to be the int conversion of a valid utf8_st8 enumeration.
Parameters
bit The flag to convert. Must be a non-zero power of 2.
Returns
An enumeration if bit is a valid parser state flag, otherwise -1.
Referenced by utf8_get_state(), and utf8_set_state().
Variable Documentation
utf8_lut
const uint16_t utf8_lut[] static constexpr
Initial value:
                                         = {
        utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) , utf8_bit(asc) ,
utf8_bit(cb3)   \           |utf8_bit(cb3_f4)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f4)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f4)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f4)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f4)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f4)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f4)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f4)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f4)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f4)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f4)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f4)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f4)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f4)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f4)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f4)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) ,
utf8_bit(cb3)   \           |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_ed)\      |utf8_bit(cb1) ,
utf8_bit(cb3)   \           |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) , utf8_bit(cb3)   \      |utf8_bit(cb3_f0)\      |utf8_bit(cb2)   \      |utf8_bit(cb2_e0)\      |utf8_bit(cb1) ,
        0 , 0 ,
        utf8_bit(lb2) , utf8_bit(lb2) , utf8_bit(lb2) , utf8_bit(lb2) , utf8_bit(lb2) , utf8_bit(lb2) , utf8_bit(lb2) , utf8_bit(lb2) , utf8_bit(lb2) , utf8_bit(lb2) , utf8_bit(lb2) , utf8_bit(lb2) , utf8_bit(lb2) , utf8_bit(lb2) , utf8_bit(lb2) , utf8_bit(lb2) , utf8_bit(lb2) , utf8_bit(lb2) , utf8_bit(lb2) , utf8_bit(lb2) , utf8_bit(lb2) , utf8_bit(lb2) , utf8_bit(lb2) , utf8_bit(lb2) , utf8_bit(lb2) , utf8_bit(lb2) , utf8_bit(lb2), utf8_bit(lb2), utf8_bit(lb2) , utf8_bit(lb2),
         utf8_bit(lb3_e0) ,
        utf8_bit(lb3) , utf8_bit(lb3) , utf8_bit(lb3) , utf8_bit(lb3) , utf8_bit(lb3) , utf8_bit(lb3) , utf8_bit(lb3) , utf8_bit(lb3) , utf8_bit(lb3) , utf8_bit(lb3) , utf8_bit(lb3), utf8_bit(lb3),
         utf8_bit(lb3_ed) ,
        utf8_bit(lb3) , utf8_bit(lb3) ,
         utf8_bit(lb4_f0) ,
        utf8_bit(lb4) , utf8_bit(lb4) , utf8_bit(lb4) ,
         utf8_bit(lb4_f4) ,
        0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0,
}
Lookup table.
Referenced by utf8_set_state().