c.utf-8: utf8 Struct Reference
utf8 Struct Reference
UTF-8 parser object.
#include <utf8.h>
Public Member Functions
struct utf8 utf8 (void)
UTF-8 parser object RAII initializer.
void utf8_reset (struct utf8 *const u8p)
Clear a UTF-8 parser object.
uint8_t const * utf8_parse_next_code_point (struct utf8 *u8p, uint8_t const *ptr)
Parse the next UTF-8 code point from a byte buffer.
char const * utf8_result (struct utf8 const *const u8p)
Get the result of the last UTF-8 code point parsing operation.
size_t utf8_size (struct utf8 const *const u8p)
Get the intended size of the last UTF-8 code point.
bool utf8_expects_leading_byte (struct utf8 const *const u8p)
Check if the parser expects a leading byte or an ASCII byte.
Data Fields
uint16_t state
uint8_t cache [5]
uint8_t error
Detailed Description
UTF-8 parser object.
Constructor & Destructor Documentation
utf8()
struct utf8 utf8 (void) inline
UTF-8 parser object RAII initializer.
Returns
A UTF-8 parser object by value.
Referenced by utf8(), utf8_expects_leading_byte(), utf8_parse_next_code_point(), utf8_reset(), utf8_result(), and utf8_size().
Member Function Documentation
utf8_expects_leading_byte()
bool utf8_expects_leading_byte (struct utf8 const *const u8p) inline
Check if the parser expects a leading byte or an ASCII byte.
Succeeds if the parser:
is in the initial parser state (utf8_ini), or
has successfully consumed an ASCII byte (utf8_asc), or
has successfully consumed the last continuation byte of a multi-byte sequence (utf8_cb1).
Parameters
u8p Pointer to the UTF-8 parser object.
Returns
true if the parser expects a leading byte or an ASCII byte.
utf8_parse_next_code_point()
uint8_t const * utf8_parse_next_code_point (struct utf8 * u8p, uint8_t const * ptr)
Parse the next UTF-8 code point from a byte buffer.
Consumes up to 4 bytes of UTF-8 encoded input until a code point is assembled or an error occurs. Returns the address of the next byte after the consumed bytes.
On valid input u8p->error is assigned 0 and the address of the next byte after the parsed code point is returned. The parsed code point's value (as UTF-8) can be retrieved by calling utf8_result() and its byte size with utf8_size().
On invalid input u8p->error is assigned EILSEQ and the address of the first invalid byte is returned (implying that invalid input is never consumed).
A null byte is treated like any ASCII value, i.e. valid if utf8_expects_leading_byte() returns true before the null byte is encountered. More specifically:
in the initial parser state (utf8_ini), or
after consuming an ASCII byte (utf8_asc), or
after consuming the last continuation byte of a multi-byte sequence (utf8_cb1). In this situation the null byte is consumed, u8p->error is assigned 0, and the address of the next byte after the null byte is returned.
If a null byte is encountered in any other situation it is an illegal byte inside a multi-byte sequence. In this case u8p->error is assigned EILSEQ and the address of the null byte is returned (i.e. the null byte is not consumed).
If the content of u8p->state is corrupt, u8p->error is assigned ENOTRECOVERABLE and the original value of ptr is returned. This is a serious error that should not occur under normal circumstances. If this happens there is a bug in the caller code or a memory corruption issue. No parsing is performed in this case.
Parameters
u8p A pointer to the UTF-8 parser object. Must not be null.
ptr A pointer to the input buffer. Must not be null.
Returns
A pointer to the byte immediately after the parsed code point, or a pointer to the first invalid byte if malformed input is encountered.
Referenced by utf8_parse_next_code_point().
utf8_reset()
void utf8_reset (struct utf8 *const u8p) inline
Clear a UTF-8 parser object.
Parameters
u8p Pointer to parser object.
utf8_result()
char const * utf8_result (struct utf8 const *const u8p) inline
Get the result of the last UTF-8 code point parsing operation.
The result is a pointer to the UTF-8 encoded code point. The result is only valid if the last parsing operation was successful, i.e. if u8p->error is 0. Otherwise the result may be incomplete.
Parameters
u8p Pointer to the UTF-8 parser object.
Returns
A pointer to the UTF-8 encoded code point.
utf8_size()
size_t utf8_size (struct utf8 const *const u8p) inline
Get the intended size of the last UTF-8 code point.
The size is the number of bytes that the last UTF-8 code point was intended to occupy in the input buffer. The size is only equal to the actual number of bytes consumed if the last parsing operation was successful, i.e. if u8p->error is 0. Otherwise the size is larger than the actual number of bytes successfully consumed.
Parameters
u8p Pointer to the UTF-8 parser object.
Returns
The intended size of the last UTF-8 code point.
The documentation for this struct was generated from the following file:
utf8.h